// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: tester.proto

package testerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tester_Unary_FullMethodName        = "/proxytester.v1.Tester/Unary"
	Tester_ServerStream_FullMethodName = "/proxytester.v1.Tester/ServerStream"
	Tester_ClientStream_FullMethodName = "/proxytester.v1.Tester/ClientStream"
	Tester_BidiStream_FullMethodName   = "/proxytester.v1.Tester/BidiStream"
)

// TesterClient is the client API for Tester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tester — сервис для проверки gRPC-прокси. Покрывает все четыре типа вызовов
// и позволяет попросить сервер задержать ответ, вернуть ошибку или ответ
// заданного размера.
type TesterClient interface {
	// Обычный вызов: запрос -> ответ.
	Unary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Сервер отправляет count ответов с интервалом interval_ms.
	ServerStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	// Клиент отправляет поток запросов, сервер отвечает одной сводкой.
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Summary], error)
	// Сервер отвечает на каждый запрос сразу же, как только его получил.
	BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type testerClient struct {
	cc grpc.ClientConnInterface
}

func NewTesterClient(cc grpc.ClientConnInterface) TesterClient {
	return &testerClient{cc}
}

func (c *testerClient) Unary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Tester_Unary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerClient) ServerStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[0], Tester_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_ServerStreamClient = grpc.ServerStreamingClient[Response]

func (c *testerClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Summary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[1], Tester_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Summary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_ClientStreamClient = grpc.ClientStreamingClient[Request, Summary]

func (c *testerClient) BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[2], Tester_BidiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_BidiStreamClient = grpc.BidiStreamingClient[Request, Response]

// TesterServer is the server API for Tester service.
// All implementations must embed UnimplementedTesterServer
// for forward compatibility.
//
// Tester — сервис для проверки gRPC-прокси. Покрывает все четыре типа вызовов
// и позволяет попросить сервер задержать ответ, вернуть ошибку или ответ
// заданного размера.
type TesterServer interface {
	// Обычный вызов: запрос -> ответ.
	Unary(context.Context, *Request) (*Response, error)
	// Сервер отправляет count ответов с интервалом interval_ms.
	ServerStream(*StreamRequest, grpc.ServerStreamingServer[Response]) error
	// Клиент отправляет поток запросов, сервер отвечает одной сводкой.
	ClientStream(grpc.ClientStreamingServer[Request, Summary]) error
	// Сервер отвечает на каждый запрос сразу же, как только его получил.
	BidiStream(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedTesterServer()
}

// UnimplementedTesterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTesterServer struct{}

func (UnimplementedTesterServer) Unary(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedTesterServer) ServerStream(*StreamRequest, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedTesterServer) ClientStream(grpc.ClientStreamingServer[Request, Summary]) error {
	return status.Error(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedTesterServer) BidiStream(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method BidiStream not implemented")
}
func (UnimplementedTesterServer) mustEmbedUnimplementedTesterServer() {}
func (UnimplementedTesterServer) testEmbeddedByValue()                {}

// UnsafeTesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TesterServer will
// result in compilation errors.
type UnsafeTesterServer interface {
	mustEmbedUnimplementedTesterServer()
}

func RegisterTesterServer(s grpc.ServiceRegistrar, srv TesterServer) {
	// If the following call panics, it indicates UnimplementedTesterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tester_ServiceDesc, srv)
}

func _Tester_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tester_Unary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServer).Unary(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tester_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TesterServer).ServerStream(m, &grpc.GenericServerStream[StreamRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_ServerStreamServer = grpc.ServerStreamingServer[Response]

func _Tester_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TesterServer).ClientStream(&grpc.GenericServerStream[Request, Summary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_ClientStreamServer = grpc.ClientStreamingServer[Request, Summary]

func _Tester_BidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TesterServer).BidiStream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_BidiStreamServer = grpc.BidiStreamingServer[Request, Response]

// Tester_ServiceDesc is the grpc.ServiceDesc for Tester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxytester.v1.Tester",
	HandlerType: (*TesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Tester_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _Tester_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _Tester_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidiStream",
			Handler:       _Tester_BidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tester.proto",
}
