// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: tester.proto

package testerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Строка, которую сервер вернёт в Response.message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Произвольные данные (для проверки больших сообщений).
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Размер payload, который сервер положит в ответ.
	ResponseSize int32 `protobuf:"varint,3,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	// Задержка перед ответом, мс.
	DelayMs int32 `protobuf:"varint,4,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// Если не 0 — сервер вернёт ошибку с этим gRPC-кодом и текстом fail_message.
	FailCode      int32  `protobuf:"varint,5,opt,name=fail_code,json=failCode,proto3" json:"fail_code,omitempty"`
	FailMessage   string `protobuf:"bytes,6,opt,name=fail_message,json=failMessage,proto3" json:"fail_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_tester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetResponseSize() int32 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *Request) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *Request) GetFailCode() int32 {
	if x != nil {
		return x.FailCode
	}
	return 0
}

func (x *Request) GetFailMessage() string {
	if x != nil {
		return x.FailMessage
	}
	return ""
}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Payload []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Порядковый номер ответа в потоке (с 1).
	Seq int64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Идентификатор экземпляра сервера — удобно для проверки балансировки.
	ServerId string `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Заголовки, которые дошли до сервера (значения -bin заголовков — в base64).
	ReceivedMetadata map[string]string `protobuf:"bytes,5,rep,name=received_metadata,json=receivedMetadata,proto3" json:"received_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Адрес клиента с точки зрения сервера (обычно адрес прокси).
	Peer string `protobuf:"bytes,6,opt,name=peer,proto3" json:"peer,omitempty"`
	// Размер payload, который получил сервер.
	ReceivedPayloadSize int32 `protobuf:"varint,7,opt,name=received_payload_size,json=receivedPayloadSize,proto3" json:"received_payload_size,omitempty"`
	// SHA-256 (hex) полученного payload — для проверки целостности данных.
	ReceivedPayloadSha256 string `protobuf:"bytes,8,opt,name=received_payload_sha256,json=receivedPayloadSha256,proto3" json:"received_payload_sha256,omitempty"`
	// Сколько миллисекунд оставалось до дедлайна вызова с точки зрения сервера
	// (0 — сервер дедлайна не видит, т.е. grpc-timeout не дошёл).
	DeadlineMs    int64 `protobuf:"varint,9,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Response) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Response) GetReceivedMetadata() map[string]string {
	if x != nil {
		return x.ReceivedMetadata
	}
	return nil
}

func (x *Response) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *Response) GetReceivedPayloadSize() int32 {
	if x != nil {
		return x.ReceivedPayloadSize
	}
	return 0
}

func (x *Response) GetReceivedPayloadSha256() string {
	if x != nil {
		return x.ReceivedPayloadSha256
	}
	return ""
}

func (x *Response) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Шаблон для каждого ответа (message, response_size, fail_code и т.д.).
	Request       *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Count         int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	IntervalMs    int32    `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_tester_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type Summary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Count            int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	ServerId         string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReceivedMetadata map[string]string      `protobuf:"bytes,4,rep,name=received_metadata,json=receivedMetadata,proto3" json:"received_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Последнее полученное сообщение.
	LastMessage   string `protobuf:"bytes,5,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_tester_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{3}
}

func (x *Summary) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Summary) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Summary) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Summary) GetReceivedMetadata() map[string]string {
	if x != nil {
		return x.ReceivedMetadata
	}
	return nil
}

func (x *Summary) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

var File_tester_proto protoreflect.FileDescriptor

const file_tester_proto_rawDesc = "" +
	"\n" +
	"\ftester.proto\x12\x0eproxytester.v1\"\xbd\x01\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\rresponse_size\x18\x03 \x01(\x05R\fresponseSize\x12\x19\n" +
	"\bdelay_ms\x18\x04 \x01(\x05R\adelayMs\x12\x1b\n" +
	"\tfail_code\x18\x05 \x01(\x05R\bfailCode\x12!\n" +
	"\ffail_message\x18\x06 \x01(\tR\vfailMessage\"\xb0\x03\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12[\n" +
	"\x11received_metadata\x18\x05 \x03(\v2..proxytester.v1.Response.ReceivedMetadataEntryR\x10receivedMetadata\x12\x12\n" +
	"\x04peer\x18\x06 \x01(\tR\x04peer\x122\n" +
	"\x15received_payload_size\x18\a \x01(\x05R\x13receivedPayloadSize\x126\n" +
	"\x17received_payload_sha256\x18\b \x01(\tR\x15receivedPayloadSha256\x12\x1f\n" +
	"\vdeadline_ms\x18\t \x01(\x03R\n" +
	"deadlineMs\x1aC\n" +
	"\x15ReceivedMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\rStreamRequest\x121\n" +
	"\arequest\x18\x01 \x01(\v2\x17.proxytester.v1.RequestR\arequest\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x05R\n" +
	"intervalMs\"\xa1\x02\n" +
	"\aSummary\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12Z\n" +
	"\x11received_metadata\x18\x04 \x03(\v2-.proxytester.v1.Summary.ReceivedMetadataEntryR\x10receivedMetadata\x12!\n" +
	"\flast_message\x18\x05 \x01(\tR\vlastMessage\x1aC\n" +
	"\x15ReceivedMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x98\x02\n" +
	"\x06Tester\x12:\n" +
	"\x05Unary\x12\x17.proxytester.v1.Request\x1a\x18.proxytester.v1.Response\x12I\n" +
	"\fServerStream\x12\x1d.proxytester.v1.StreamRequest\x1a\x18.proxytester.v1.Response0\x01\x12B\n" +
	"\fClientStream\x12\x17.proxytester.v1.Request\x1a\x17.proxytester.v1.Summary(\x01\x12C\n" +
	"\n" +
	"BidiStream\x12\x17.proxytester.v1.Request\x1a\x18.proxytester.v1.Response(\x010\x01B`\n" +
	"!com.example.grpcproxytester.protoP\x01Z9github.com/Gramzes/LocationApp/grpc-proxy-tester/testerpbb\x06proto3"

var (
	file_tester_proto_rawDescOnce sync.Once
	file_tester_proto_rawDescData []byte
)

func file_tester_proto_rawDescGZIP() []byte {
	file_tester_proto_rawDescOnce.Do(func() {
		file_tester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tester_proto_rawDesc), len(file_tester_proto_rawDesc)))
	})
	return file_tester_proto_rawDescData
}

var file_tester_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tester_proto_goTypes = []any{
	(*Request)(nil),       // 0: proxytester.v1.Request
	(*Response)(nil),      // 1: proxytester.v1.Response
	(*StreamRequest)(nil), // 2: proxytester.v1.StreamRequest
	(*Summary)(nil),       // 3: proxytester.v1.Summary
	nil,                   // 4: proxytester.v1.Response.ReceivedMetadataEntry
	nil,                   // 5: proxytester.v1.Summary.ReceivedMetadataEntry
}
var file_tester_proto_depIdxs = []int32{
	4, // 0: proxytester.v1.Response.received_metadata:type_name -> proxytester.v1.Response.ReceivedMetadataEntry
	0, // 1: proxytester.v1.StreamRequest.request:type_name -> proxytester.v1.Request
	5, // 2: proxytester.v1.Summary.received_metadata:type_name -> proxytester.v1.Summary.ReceivedMetadataEntry
	0, // 3: proxytester.v1.Tester.Unary:input_type -> proxytester.v1.Request
	2, // 4: proxytester.v1.Tester.ServerStream:input_type -> proxytester.v1.StreamRequest
	0, // 5: proxytester.v1.Tester.ClientStream:input_type -> proxytester.v1.Request
	0, // 6: proxytester.v1.Tester.BidiStream:input_type -> proxytester.v1.Request
	1, // 7: proxytester.v1.Tester.Unary:output_type -> proxytester.v1.Response
	1, // 8: proxytester.v1.Tester.ServerStream:output_type -> proxytester.v1.Response
	3, // 9: proxytester.v1.Tester.ClientStream:output_type -> proxytester.v1.Summary
	1, // 10: proxytester.v1.Tester.BidiStream:output_type -> proxytester.v1.Response
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tester_proto_init() }
func file_tester_proto_init() {
	if File_tester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tester_proto_rawDesc), len(file_tester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tester_proto_goTypes,
		DependencyIndexes: file_tester_proto_depIdxs,
		MessageInfos:      file_tester_proto_msgTypes,
	}.Build()
	File_tester_proto = out.File
	file_tester_proto_goTypes = nil
	file_tester_proto_depIdxs = nil
}
